// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHN7FbavZczAWPi9nlzOx33h3oFNnEduw',
    appId: '1:1038351635586:web:b00b84be95819b6d67d09b',
    messagingSenderId: '1038351635586',
    projectId: 'movieexplorer-app',
    authDomain: 'movieexplorer-app.firebaseapp.com',
    storageBucket: 'movieexplorer-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-KJGL1JxL_D5Q94PsSB8m15LNzwnMgE',
    appId: '1:1038351635586:android:1ce26e101654553067d09b',
    messagingSenderId: '1038351635586',
    projectId: 'movieexplorer-app',
    storageBucket: 'movieexplorer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnrpghtwuvCcNoDbroHlCWYpAWlYilVY8',
    appId: '1:1038351635586:ios:e1f9833ae50812f067d09b',
    messagingSenderId: '1038351635586',
    projectId: 'movieexplorer-app',
    storageBucket: 'movieexplorer-app.firebasestorage.app',
    iosBundleId: 'com.example.movieExplorer',
  );
}
